---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle11g-pvc
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-path"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle11g
  labels:
    app: oracledb
spec:
  selector:
    matchLabels:
      app: oracledb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracledb
    spec:
      containers:
      - image: jaspeen/oracle-xe-11g
        name: oracle11g-db
        ports:
        - containerPort: 1521
          name: oracle11g-port
        volumeMounts:
        - name: oracle11g-pv
          mountPath: /u01/app/oracle
      imagePullSecrets:
        - name: oradocreg
      securityContext:
        fsGroup: 54321
      volumes:
        - name: oracle11g-pv
          persistentVolumeClaim:
            claimName: oracle11g-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: oracle11g-svc
spec:
 type: NodePort
 selector:
   app: oracledb
 ports:
   - name: client
     protocol: TCP
     port: 1521
     nodePort: 31521
 selector:
   app: oracledb

