apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle-demo
  namespace: argocd
  labels:
    app: gradle-demo
spec:
  selector:
    matchLabels:
      app: gradle-demo
  template:
    metadata:
      labels:
        app: gradle-demo
    spec:
      containers:
      - image: kw01:30005/gradle-demo:dev
        imagePullPolicy: Always
        name: gradle-demo