apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-to-image
spec:
  params:
    - name: git-url 
    - name: revision
      default: master
    - name: image-name 
    - name: insecure-registry
      default: "false"
  workspaces:
    - name: source 
  tasks:
    - name: clone-sources
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      taskRef:
        name: jib-maven
      runAfter:
        - clone-sources
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: INSECUREREGISTRY
          value: $(params.insecure-registry)
      workspaces:
        - name: source
          workspace: source
