apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kb-msp-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: git-to-image
  params:
  - name: revision
    value: master
  - name: insecure-registry
    value: "true"
  - name: git-url
    value: http://192.168.121.151:30079/scm/kbdev/kb-dev.git
  - name: image-name
    value: "192.168.121.151:30005/kb/kb-sample:dev"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: kb-msp-build-pvc

