---
apiVersion: v1
kind: Namespace
metadata:
  name: confluence

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: confluence
  name: confluence-pvc
  labels:
    app: confluence
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "local-path"

---
apiVersion: v1
kind: Service
metadata:
  namespace: confluence
  name: confluence
  labels:
    app: confluence
spec:
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30080
    name: ui
  - port: 8091
    targetPort: 8091
    nodePort: 30081
    name: internal
  type: NodePort
  selector:
    app: confluence
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: confluence
  name: confluence
spec:
  selector:
    matchLabels:
      app: confluence
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: confluence
    spec:
      containers:
      - image: atlassian/confluence-server:7.8-jdk8
        name: confluence
        ports:
        - containerPort: 8090
          name: ui
        - containerPort: 8091
          name: internal
        volumeMounts:
        - name: local-home
          mountPath: /var/atlassian/application-data/confluence
      volumes:
        - name: local-home
          persistentVolumeClaim:
            claimName: confluence-pvc

