
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-dockerfile

spec:
  params:
  - name: path
    default: "."
  - name: filename
    default: Dockerfile

  workspaces:
  - name: source

  results:
  - name: exists
    description: indicates whether dockerfile exists or missing

  steps:
  - name: check-file
    image: alpine
    script: |
            if test -f $(workspaces.source.path)/$(params.path)/$(params.filename); 
            then
              printf yes | tee /tekton/results/exists
            else
              printf no | tee /tekton/results/exists
            fi
            echo "Dockerfile exist ?" + $(results.exists)

